# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 590ff77301ddb5380ed359afa310f86f5bc7cf051f164dbf3e5bcf051648e0eb390e6bcd0729b7a2fae0cb97a85d0aa9beebb77ae308feb4d8f628755b79f057
  stripe_publishable_key: pk_test_xyDScMVIlPXMkeyTRSoKrW8i
  stripe_secret_key: sk_test_J2Ls4vhi9agghhoIvAUKkH7d

test:
  secret_key_base: 8c56a41133e390696d385848f45b408092ca5a6afb98e74eebd859b486064fc7626d41732e0f07b2185f2bde3a612f7691e3915fb4a288fd7f98646072e630ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
